### ISSUE TITLE
nuxt vite  error with file  (.JPG) on assets folder

### ISSUE THREAD

**Issue by silvesterwali** [nuxt/vite#105]
### Versions

nuxt-vite: v0.0.36
nuxt:v2.15.3 

### Description

i just install nuxt 2.15.3 and nuxt vite 0.0.36  when i yarn dev
i just get error like bellow ```

 ERROR  Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .JPG file format.

  at formatError (node_modules\vite\dist\node\chunks\dep-6f1d3d8c.js:43442:46)
  at TransformContext.error (node_modules\vite\dist\node\chunks\dep-6f1d3d8c.js:43438:19)
  at TransformContext.transform (node_modules\vite\dist\node\chunks\dep-6f1d3d8c.js:44921:22)
  at async Object.transform (node_modules\vite\dist\node\chunks\dep-6f1d3d8c.js:43640:30)
  at async transformRequest (node_modules\vite\dist\node\chunks\dep-6f1d3d8c.js:59299:29)
  at async warmup (node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:356:5)
  at async Promise.all (index 0)
  at async warmup (node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:358:5)
  at async Promise.all (index 0)
  at async warmup (node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:358:5)
  at async Promise.all (index 1)
  at async warmup (node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:358:5)
  at async Promise.all (index 15)
  at async warmup (node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:358:5)
  at async Promise.all (index 5)
  at async warmup (node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:358:5)

 ERROR  [rollup-plugin-dynamic-import-variables] Unexpected character '�' (1:0)                                             

```

here is my package.json

``` 
{
  "name": "nuxt-saya",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint": "yarn lint:js",
    "lintfix": "eslint --fix --ext .js,.vue --ignore-path .gitignore ."
  },
  "lint-staged": {
    "*.{js,vue}": "eslint"
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "lint-staged"
    }
  },
  "dependencies": {
    "@mdi/font": "5.8.55",
    "@nuxt/content": "^1.13.1",
    "@nuxtjs/axios": "^5.12.5",
    "@nuxtjs/pwa": "^3.3.5",
    "core-js": "^3.8.3",
    "css-loader": "^5.1.3",
    "dotenv": "^8.2.0",
    "moment": "^2.29.1",
    "nuxt": "^2.15.3",
    "socket.io-client": "^3.1.2"
  },
  "devDependencies": {
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@nuxtjs/eslint-config": "^5.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/vuetify": "^1.11.3",
    "babel-eslint": "^10.1.0",
    "deepmerge": "^4.2.2",
    "eslint": "^7.18.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.5.0",
    "husky": "^4.3.8",
    "lint-staged": "^10.5.3",
    "nuxt-vite": "^0.0.36",
    "prettier": "^2.2.1",
    "sass": "^1.32.8",
    "sass-loader": "10"
  }
}

```

and my nuxt.config.js 

```
import colors from 'vuetify/es5/util/colors'
// import '@mdi/font/css/materialdesignicons.css'
require('dotenv').config()
export default {
  target: 'server',
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    titleTemplate: '%s - My nuxt',
    title: 'Prototype',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/logosaa.png' }],
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: ['~/assets/css/custom.css'],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: false,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    [
      '@nuxtjs/eslint-module',
      {
        fix: true,
      },
    ],
    // https://go.nuxtjs.dev/vuetify
    '@nuxtjs/vuetify',
    'nuxt-vite',
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    '@nuxt/content',
  ],
  vuetify: {
    customVariables: ['~/assets/variables.scss'],
    treeShake: true,
    icons: {
      iconfont: 'mdi', // default - only for display purposes
    },
    theme: {
      themes: {
        dark: {
          primary: '#1976D2',
          secondary: '#424242',
          accent: '#82B1FF',
          error: '#FF5252',
          info: '#2196F3',
          success: '#4CAF50',
          warning: '#FFC107',
        },
        light: {
          primary: colors.blue.accent3,
          secondary: '#b0bec5',
          accent: '#8c9eff',
          error: '#b71c1c',
          info: '#2196F3',
          success: '#4CAF50',
          warning: '#FFC107',
        },
      },
    },
  },

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {},
  // PWA module configuration: https://go.nuxtjs.dev/pwa

  loaders: {
    vue: {
      prettify: false,
    },
  },
  generate: {
    fallback: true,
  },

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {},
}

 ```
before i add nuxt vite is still running normal as well but now i get error 


thank's for any help

**Comment by antfu** [comment]
Can you share a minimal reproduction and format your issue description? Thanks.
