### ISSUE TITLE
The project is loading slowly

### ISSUE THREAD

**Issue by Rasool-deldar** [nuxt/vite#114]
The output project takes less than 5 seconds, but it takes about 10 minutes or more to load in the browser in dev mode. Please fix this problem (:

```
"dependencies": {
    "core-js": "^3.6.5",
    "nuxt": "^2.15.3"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^3.1.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "@nuxtjs/vuetify": "^1.11.2",
    "@vue/test-utils": "^1.1.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.5.0",
    "eslint": "^7.10.0",
    "eslint-plugin-nuxt": "^1.0.0",
    "jest": "^26.5.0",
    "nuxt-vite": "0.0.36",
    "vue-jest": "^3.0.4"
  }
```

**Comment by Rasool-deldar** [comment]
> @Rasool-deldar Could you provide a reproduction? That is ... definitely longer than expected 😆

No, unfortunately I can not because the program runs on codesandbox using nuxt-vite fast.
But it takes about 10 minutes on the system, I do not know exactly where the problem comes from

**Comment by antfu** [comment]
Close due to inactive
