### ISSUE TITLE
Nuxt components support

### ISSUE THREAD

**Issue by danielroe** [nuxt/vite#12]
https://github.com/nuxt/components/pull/157

**Comment by pi0** [comment]
I think it would be better finding a solution for root cause. There are many more plugins dont have default export. It might be fixed with a rollup plugin

**Comment by nathanchase** [comment]
> I think it would be better finding a solution for root cause. There are many more plugins dont have default export. It might be fixed with a rollup plugin

Perhaps https://github.com/TeleworkInc/rollup-plugin-export-default ?

**Comment by pi0** [comment]
@nathanchase Yes i'm looking for similar way. That plugin is using `renderChunk` which is too late for vite.
