### ISSUE TITLE
Error when using for await

### ISSUE THREAD

**Issue by TheNoim** [nuxt/vite#122]
### Versions

nuxt-vite: 0.0.36
nuxt: 2.14.6

### Reproduction

https://codesandbox.io/s/vite-for-await-bug-40fb6

### Description

You can't use for await, because vite will throw an error. 

```

> html:/sandbox/pages/index.vue:18:8: error: Expected "(" but found "void"
    18 │     for void (let num of asyncGenerator()) {
       ╵         ~~~~
```

Actual code:

```javascript
for await (let num of asyncGenerator()) {
      console.log(num);
}
```

**Comment by antfu** [comment]
It seems like upgrading to v0.2.2 solves this.
