### ISSUE TITLE
bug report:The latest version of plugin causes rendering errors

### ISSUE THREAD

**Issue by gzg1023** [nuxt/vite#124]
demo:https://codesandbox.io/s/fervent-diffie-wo5lk

If these three plug-ins are used by colleagues, it will lead to fatal rendering errors. There are two (__nuxt) nodes

nuxt-vite: : v0.0.36
nuxt:  v2.15.0
nuxt-property-decorator: 2.9.1

**Comment by gzg1023** [comment]
I don't know if it's nuxt-vite or nuxt-property-decorator, but using them together will cause this problem

**Comment by gzg1023** [comment]
like this：
![WechatIMG3145.png](https://i.loli.net/2021/04/20/hJvwqTEFsRODdKk.png)

or(new project)：
![WechatIMG3181.png](https://i.loli.net/2021/04/20/D7M1Gvy32rlxzA8.png)


When these three plug-ins (nuxt, nuxt-vite, nuxt-property-decorator) are used together, there will be many problems.
Sometimes it appears, sometimes it doesn't, and I don't know what to do

**Comment by nicoeg** [comment]
I'm receiving these errors without the use of nuxt-property-decorator

**Comment by gzg1023** [comment]
> I'm receiving these errors without the use of nuxt-property-decorator

Well, that's nuxt-vite  bug

**Comment by bnd170** [comment]
Hey, @gzg1023 can you share your nuxt.config, please?

**Comment by antfu** [comment]
It should be fixed in the latest version. Can you re-verify? Thanks.
