### ISSUE TITLE
require is not defined when using nuxtjs/composition-api

### ISSUE THREAD

**Issue by kylemod** [nuxt/vite#134]
### Versions

nuxt-vite: 0.0.37
nuxt: 2.15.4

### Reproduction

A fresh install of nuxt app and nuxtjs/composition-api

### Description

It just says `require is not defined
at http://localhost:3000/@fs/my/storage/path/nuxt-vite/node_modules/@nuxtjs/composition-api/dist/register.js?v=c9e46a53:3:13` in my console 

And when i use a hook like onMounted, my terminal printed `ERROR  [Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().`

**Comment by yaiks** [comment]
Hey @kylemod, I've also run into this issue and I **guess** this is a bug on the `@nuxt/composition-api` library. I opened an [issue there](https://github.com/nuxt-community/composition-api/issues/476) with my findings, feel free to jump in and talk about your experience.

**Comment by kylemod** [comment]
Closing issue. See [rework composition api registration](https://github.com/nuxt-community/composition-api/pull/484)

**Comment by manoj-mukherjee-maersk** [comment]
img if using require giving same error `<img
            :src="require(`~/assets/icons/${menuItem.iconName}.svg`)"
          />`
any solution?

**Comment by justice47** [comment]
> img if using require giving same error `<img :src="require(`~/assets/icons/${menuItem.iconName}.svg`)" />`
> any solution?

Did you find a solution?
I'm running into this too

**Comment by cyanerd** [comment]
> img if using require giving same error `<img :src="require(`~/assets/icons/${menuItem.iconName}.svg`)" />` any solution?

same problem. did u find any solution?

**Comment by kayoderock** [comment]
@cyanerd you are most likely using Vite for your packing.

**Comment by kayoderock** [comment]
In template:
`<img class="bp-icon" :src="imgUrl" alt="">`

In the script:
`mounted () { this.imgUrl = new URL(`../assets/img/${this.icon}.svg`, import.meta.url) }`
