### ISSUE TITLE
runder function nonsupport

### ISSUE THREAD

**Issue by a314949730** [nuxt/vite#140]
### Versions

nuxt-vite: v0.1.0
nuxt: v2.15.3

### Description

![image](https://user-images.githubusercontent.com/13251658/118443604-ad571780-b71e-11eb-8215-ef7f583a0010.png)

**Comment by Casseil-1996** [comment]
![image](https://user-images.githubusercontent.com/33025894/131774108-5dfff679-aac3-451b-b152-a00516e5da9f.png)
![image](https://user-images.githubusercontent.com/33025894/131774233-2b0f4c86-52fc-465a-9916-90b427ec61ce.png)
I think I may have encountered the same problem

**Comment by antfu** [comment]
Close due to inactive.
