### ISSUE TITLE
Can't use element2?

### ISSUE THREAD

**Issue by chaos-zhu** [nuxt/vite#150]
### Versions

"nuxt-vite": "^0.1.1",
"nuxt": "^2.15.6"

### Description

**Once the reference document was fully configured, it started quickly but failed to load the page**

![image](https://user-images.githubusercontent.com/44160914/120145464-232aab00-c216-11eb-979f-61af1ed15d8f.png)

**I looked up information on the network and found that it could be caused by vite not compatible with element2?Do I have to upgrade to element3?That would cost too much**

```js
Uncaught TypeError: Cannot read property '$isServer' of undefined
```

**Comment by liuqian1996** [comment]
Me too, but `nuxt-vite@0.1.0` works

**Comment by liuqian1996** [comment]
Element question [🚀](https://github.com/ElemeFE/element/issues/21005)
