### ISSUE TITLE
The vite's public folder conflicts with the nuxt's static folder.

### ISSUE THREAD

**Issue by yzqdev** [nuxt/vite#158]
Using nuxt-vite, special public directory is under your project root. Assets in this directory will be served at root path /;  While using the command nuxt ,assets in the 'static' directory will be served at root path / ; So it is ambugious when we use nuxt-vite, we should use public as th root path / or the static folder as root path /?
### Versions

nuxt-vite: v0.1.1
nuxt: 2.15.7

### Reproduction
Now using the static as root path /, sometimes the images could be found ,sometime not;
**the logo image could be found, while the default.png couldn't just as below**
Below is my folder structure. 
![image](https://user-images.githubusercontent.com/20037151/123586292-1601db80-d817-11eb-8b66-988dbf3e829f.png)

![image](https://user-images.githubusercontent.com/20037151/123586493-62e5b200-d817-11eb-8cf2-1d58eab6f7b5.png)

![image](https://user-images.githubusercontent.com/20037151/123586099-d0dda980-d816-11eb-8987-e2d7abcfdd29.png)

**Comment by phamhongphuc** [comment]
I think updating the `publicDir` will work but after that, I got a different issue.

### Reproduction
```html
<template>
  <!-- /static/favicon.png -->
  <img src="/favicon.png" />
</template>
```

```js
// nuxt.config.js
export default {
   // ...
   vite: {
     publicDir: resolve(__dirname, 'static'),
   }
}
```

### Results

Terminal/cmd doesn't report any errors. But I got an error in the browser.

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "image/png".
Strict MIME type checking is enforced for module scripts per HTML spec.

TypeError: Failed to fetch dynamically imported module:
```

![image](https://user-images.githubusercontent.com/11532116/125806626-2290c60c-a074-4b20-aa7c-a16bff93b0ea.png)
