### ISSUE TITLE
support page middleware

### ISSUE THREAD

**Issue by c5n8** [nuxt/vite#16]
Error in browser dev tools console:
```
Uncaught ReferenceError: require is not defined at middleware.js:3
```

`middleware.js` in dev tools `Sources` tab:
```
const middleware = {}

middleware['admin'] = require('../middleware/admin.js')
middleware['admin'] = middleware['admin'].default || middleware['admin']

...

export default middleware
```

**Comment by pi0** [comment]
Hi @c5n8 thanks for reporting. Some on nuxt templates are still using require syntax. This problem should probably be fixed in upstream or via alternative template we provide by module... Until then page middleware are not supported by this module

**Comment by madsh93** [comment]
@pi0 Readme states that middleware is supported. Is this fixed?

**Comment by pi0** [comment]
Yes. Just added middleware support! Please report any issue if encountered for using them.
