### ISSUE TITLE
vue-property-decorator need to be supported

### ISSUE THREAD

**Issue by FurryWolfX** [nuxt/vite#161]
### Version
"nuxt": "^2.15.7",
"nuxt-vite": "^0.1.1",

### Is your feature request related to a problem? Please describe.
report `error: Unexpected "@"` when use decorator

**Comment by bnd170** [comment]
Any updates?

**Comment by bnd170** [comment]
@FurryWolfX please, check if your component `<script>` is tagged as ` lang="ts"`

**Comment by FurryWolfX** [comment]
Yes, I find some scripts aren't tagged as ts
