### ISSUE TITLE
it's bug?

### ISSUE THREAD

**Issue by gui8515** [nuxt/vite#163]
### Description

$ npm run dev

> frontend@1.0.0 dev C:\Users\Guilherme\Documents\GitHub\T7\frontend
> nuxt

🧪  Vite mode is experimental and some nuxt modules might be incompatible                                               21:37:50
    If found a bug, please report via https://github.com/nuxt/vite/issues with a minimal reproduction.
    Unstable server-side rendering is enabled

   ╭───────────────────────────────────────────────────────╮
   │                                                       │
   │   Nuxt @ v2.15.7                                      │
   │                                                       │
   │   ▸ Environment: development                          │
   │   ▸ Rendering:   server-side                          │
   │   ▸ Target:      server                               │
   │                                                       │
   │   Listening: http://localhost:3000/                   │
   │                                                       │
   │   ⚡  Vite Mode Enabled (v0.1.1)                      │ 
   │   Tailwind Viewer: http://localhost:3000/_tailwind/   │
   │                                                       │
   ╰───────────────────────────────────────────────────────╯

i Preparing project for development                                                                                    21:37:53
i Initial build may take a while                                                                                       21:37:53
i Discovered Components: .nuxt/components/readme.md                                                                    21:37:53
√ Builder initialized                                                                                                  21:37:53
√ Nuxt files generated                                                                                                 21:37:54

 WARN  Unrestricted file system access to "/@id/defaultexport:C:/Users/Guilherme/Documents/GitHub/T7/frontend/.nuxt/components/plugin.js"

 WARN  For security concerns, accessing files outside of serving allow list will be restricted by default in the future version of Vite. Refer to https://vitejs.dev/config/#server-fs-allow for more details.

 WARN  Unrestricted file system access to "/@id/defaultexport:C:/Users/Guilherme/Documents/GitHub/T7/frontend/.nuxt/workbox.js"  

 WARN  Unrestricted file system access to "/@id/defaultexport:C:/Users/Guilherme/Documents/GitHub/T7/frontend/.nuxt/pwa/meta.plugin.js"

 WARN  Unrestricted file system access to "/@id/defaultexport:C:/Users/Guilherme/Documents/GitHub/T7/frontend/.nuxt/pwa/icon.plugin.js"

 WARN  Unrestricted file system access to "/@id/defaultexport:C:/Users/Guilherme/Documents/GitHub/T7/frontend/.nuxt/axios.js"    

 WARN  Unrestricted file system access to "/@id/__x00__/vite/vueComponentNormalizer"                                   21:37:58  

 WARN  Unrestricted file system access to "/@id/__x00__/vite/vueHotReload"                                             21:37:58  

i Vite warmed up in 11481ms                                                                                            21:38:09

 WARN  Unrestricted file system access to "/__webpack_hmr/client"                                                      21:38:23  

i Waiting for file changes                                                                                             21:39:35
i Memory usage: 659 MB (RSS: 1.02 GB)                                                                                  21:39:35
i Listening on: http://localhost:3000/                                                                                 21:39:35

**Comment by sctnightcore** [comment]
I have this problem too.

**Comment by thevuong** [comment]
Adding this option will ignore error logging.

```js
vite: {
  server: {
    fs: {
      strict: false,
    },
  },
},
```

https://vitejs.dev/config/#server-fs-strict

**Comment by antfu** [comment]
Should works in 0.2.x by default.
