### ISSUE TITLE
Build Nuxt project with Vite instead of Webpack

### ISSUE THREAD

**Issue by sto3psl** [nuxt/vite#167]
### Is your feature request related to a problem? Please describe.

When I started using `nuxt-vite` with my project, everything worked smoothly and my dev environment is pretty fast now, this is great and it was very painless to switch! But when I tried building, I noticed that my projects still uses Webpack. This makes sense and you kind of say that in the docs:

> This package allows using Vite instead of Webpack during development with Nuxt

**Are there any plans to support building with Vite and getting rid of Webpack completely?**   
(Or maybe it's already possible with some configuration).

### Describe the solution you'd like

When I run `nuxt build`, I want nuxt to build my project with Vite instead of Webpack.

---

Thanks a lot for this module and I'm looking forward to future development and what awesome stuff you are going to develop!

**Comment by mirabledictu** [comment]
Sad this project looks abandoned because they're focusing on Nuxt v3 now.
