### ISSUE TITLE
Using less in SFC cause error: Preprocessor dependency "less" not found

### ISSUE THREAD

**Issue by Wiihame** [nuxt/vite#171]
### Versions

nuxt-vite: 0.1.1
nuxt: 2.15.7

### Reproduction

https://github.com/Wiihame/nuxt-vite-less

### Description

When I use less in style tag in SFC, vite cause preprocessor dependency error for less. like this:
code:
![image](https://user-images.githubusercontent.com/20560592/129033411-e96e3ef3-5ebf-4ad0-a2aa-be8b38fe431a.png)

terminal:
![image](https://user-images.githubusercontent.com/20560592/129033072-4bd8def4-5b57-43c6-aa62-aa0615dbb8fb.png)

**Comment by BobbieGoede** [comment]
I'm having the same issue but with sass/scss, downgrading to `nuxt-vite@0.1.0` resolves this, not sure what causes it though.

**Comment by Wiihame** [comment]
> I'm having the same issue but with sass/scss, downgrading to `nuxt-vite@0.1.0` resolves this, not sure what causes it though.

Thanks. I had solved this problem by downgrading to `vite@2.3.4`, also not sure what causes it though😂

**Comment by BobbieGoede** [comment]
Updating to `nuxt-vite@0.2.4` has fixed this issue for me (see #162). Can imagine it will work when using less preprocessor as well @Wiihame.

**Comment by Wiihame** [comment]
> Updating to `nuxt-vite@0.2.4` has fixed this issue for me (see #162). Can imagine it will work when using less preprocessor as well @Wiihame.

Thanks! I will try it later
