### ISSUE TITLE
Monorepo or PNPM

### ISSUE THREAD

**Issue by antfu** [nuxt/vite#174]
Currently, each folder have their own `yarn.lock` - `docs/` `demo/` which makes the packages separate and time consuming to install and maintain. Thinking of using one of the following solution

- Use yarn workspaces, which we will need to overhaul the project structure as yarn does not allow to have root `package.json` to be a public project. Which also make the scripts of releasing a bit harder (might need to introduce `lerna`?) 
- Switch to `pnpm`, as pnpm allows to have root `package.json` to be the main package. It also provide `pnpm -r run [script]` and `pnpm -r publish` to manage the packages without extra dependencies.

/cc @pi0

**Comment by pi0** [comment]
- Yarn is standard package manager we use for maintaining nuxt repos
- Docs intentionally has it's own yarn lock so for docs deployment we don't install module dev dependencies like jest
- Examples, Demos and Fixtures should use top level dev dependencies

**Comment by antfu** [comment]
Yeah I don't really mind `docs/`, but `demo/` also has its own `package.json` / `yarn.lock` which I found trouble testing the package. Or should I use `test/fixture` to test?
