### ISSUE TITLE
support jsx in js function

### ISSUE THREAD

**Issue by Binaryify** [nuxt/vite#178]
### Versions

nuxt-vite:  0.1.3
nuxt: 2.15.8

### Reproduction
use jsx in .vue file, will show "error: Unexpected "<""
```
const someConfig = [
    {
      title: 'Start time',
      align: 'right',
      key: 'startTime',
      render(h){
        return <span>2021-01-01</span>;
        
      }
    },
  ];
```

### Description
some UI libary like iView using jsx in their table components, but nuxt-vite seem like don't support use jsx in js function

**Comment by Casseil-1996** [comment]
小哥，你搞定了么？

**Comment by antfu** [comment]
Have you set `<script lang="jsx">`? Can you provide a minimal reproduction? Thanks

**Comment by Binaryify** [comment]
seem like this problem already fixed now
