### ISSUE TITLE
error: No loader is configured for ".vue" files: components/ComponentName.vue

### ISSUE THREAD

**Issue by jericopulvera** [nuxt/vite#18]
tried it just now with my SPA project.

**Comment by frenchrabbit** [comment]
Same here:
 > html:/Users/user/Projects/big-vue/pages/news/_id.vue:6:28: error: No loader is configured for ".vue" files: components/v3/v3-promo.vue
    6 │       v3Promo: () => import('@/components/v3/v3-promo'),
      ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by heyarviind** [comment]
I am having the same issue with layouts...

**Comment by pierredup** [comment]
Vue files need to be imported with the `.vue` extension. Without the extension, it won't work. E.G

```js
// before
import MyButton from '@/components/util/my-button';

// after
import MyButton from '@/components/util/my-button.vue';
```

**Comment by heyarviind** [comment]
@pierredup it worked

**Comment by jericopulvera** [comment]
Worked for me as well.

## Here's a shortcut that worked for me if you have many lines without .vue

### Step 1:  Add .vue at the end of lines that contains @/components using search in regex mode.

Type in Regex Search

```
^.*(@/components).*$
```

Replace with
```
$0.vue
```

Execute Replace All

### Step 2: Search and Replace ";.vue to .vue";

**Comment by FelixGraf** [comment]
Not sure if this issue should be closed. I think it would be cool, if it would work out of the box - without having to add `.vue` extension to every import.

**Comment by jericopulvera** [comment]
> Not sure if this issue should be closed. I think it would be cool, if it would work out of the box - without having to add `.vue` extension to every import.

You've got a point. I'll reopen this and wait for the maintainers decision.

**Comment by pierredup** [comment]
> I think it would be cool, if it would work out of the box - without having to add .vue extension to every import

This is not an issue with this plugin but is by design how Vite works.

See https://github.com/vitejs/vite/issues/178#issuecomment-630138450 and https://twitter.com/youyuxi/status/1288859415878283264

**Comment by FelixGraf** [comment]
> This is not an issue with this plugin but is by design how Vite works.

Good to know, thanks!

**Comment by jericopulvera** [comment]
I will close this now as it has nothing to do with the plugin.
