### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by xanzhu** [nuxt/vite#212]
### Versions

nuxt-vite: 0.3.1 
nuxt: 2.15.7 

### Reproduction
Reproduces on clean install, run `` yarn dev `` -  https://github.com/xanzhu/2102101

### Description
Generating error during the build process.

![Screenshot 2021-10-02 205444](https://user-images.githubusercontent.com/34955679/135709039-67eda8c6-c8b3-4eea-a28a-a99249c80508.png)

Functioned normally via v0.2.4
Is there any extra configuration needed in this new version?

**Comment by IshanKBG** [comment]
ya same happended with me but when running dev server
here is my [issue](https://github.com/nuxt/vite/issues/213)

**Comment by pi0** [comment]
Hi @xanzhu and thanks for reporting. Issue related to p-debounce is resolved in `nuxt-vite@^0.3.2` (confirmed on reproduction)
