### ISSUE TITLE
vite server on a nuxt application takes way to long to start

### ISSUE THREAD

**Issue by tinegaCollins** [nuxt/vite#243]
### Versions

nuxt-vite: 
nuxt: 

### Description

the vite server takes up to 15 minutes to start, i thought this was a device problem so i run it on my pc but the problem persists. what do i do?

**Comment by nurdus** [comment]
I got the same problem. Additional long time for hot reload:
```
√ Vite server built in 270ms 
√ Vite server built in 339ms                                                                                                                                                                                    
√ Vite server built in 1465877ms
```
Do you have any idea?

**Comment by tinegaCollins** [comment]
what kind of device are you using

**Comment by nurdus** [comment]
Laptop: Core i3CPU @ 2.20GHz, RAM 8Gb, Win 10 (x64).

**Comment by tinegaCollins** [comment]
I fixed this problem by getting a new pc

**Comment by nurdus** [comment]
Hmm, your solution help me too. I setup vps, and everything is OK ))
