### ISSUE TITLE
Cannot find module 'ky-universal/node' (http module)

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt/vite#25]
Doesn't work with Nuxt SSR.
![image](https://user-images.githubusercontent.com/69633530/109306509-8f74c780-783f-11eb-8f34-7f010d6d5fe6.png)

**Comment by pi0** [comment]
Hi @florian-lefebvre. You you please provide a reproduction repo?

**Comment by productfrontenddeveloper** [comment]
some vite problem toast nuxt module  [#404](https://github.com/nuxt-community/community-modules/issues/404)

**Comment by pi0** [comment]
We was missing `client|server` plugin filter. Hopefully problem is now solved in 0.0.7

**Comment by florian-lefebvre** [comment]
With a very simple project, it works so the problem must be caused by a module. I'm looking into it, I'll let you know.

**Comment by florian-lefebvre** [comment]
I didn't manage to reproduce this error, however I had one with both nuxt-i18n and @nuxtjs/strapi: **Cannot find module 'ky-universal/node' from 'F:\CONTENT\DEVELOPPEMENT\WEB\TESTS\reproduction repos\nuxt-vite-issues-25'**.
Also noticed that every time I (un)install a package with yarn I get the following warning:
```bash
[3/4] Linking dependencies...
warning "nuxt-vite > vite-plugin-vue2 > @vue/compiler-sfc@3.0.6" has incorrect peer dependency "vue@3.0.6".
[4/4] Building fresh packages...
```
Here is a repoduction repo with both modules: https://github.com/florian-lefebvre/nuxt-vite-issues-25
