### ISSUE TITLE
Linking to dynamic route with the nuxtlink 

### ISSUE THREAD

**Issue by Montcat** [nuxt/vite#256]
### Versions

nuxt-vite: 
nuxt: 

### Description

This code sample:
<Nuxtlink to="`/products/${id}`">

Was give me a 404 page not found : /`product/${id}`

Don't know how wrong my code is but I strongly think it's a bug

**Comment by Montcat** [comment]
Ok sorry, might no be that much of a problem because it worked when I closed and re-ran the server.

**Comment by danielroe** [comment]
Also note that this module is deprecated in favour of either [Nuxt Bridge](https://github.com/nuxt/bridge) or [Nuxt 3](https://github.com/nuxt/framework).
