### ISSUE TITLE
Error in /node_modules/.vite/servyer and The requested module '/content/query-builder.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by filippolcr** [nuxt/vite#38]
### Versions

nuxt-vite:  v0.0.12
nuxt:  v2.15.2 

### Reproduction
https://github.com/eazybike/website

### Description

yarn dev show an error:
**ENOENT: no such file or directory, rmdir '/Users/filippo/Development/nuxt-vite/node_modules/.vite/servyer/temp/temp**

Client and server compiled sucessfully

In console on localhost:3000
**Uncaught SyntaxError: The requested module '/content/query-builder.js' does not provide an export named 'default'**

**Comment by productfrontenddeveloper** [comment]
similar #14 ? thats true

**Comment by pi0** [comment]
Yes dup of #14 for content module support :)
