### ISSUE TITLE
Provide ability to pass configuration to vite-plugin-vue2

### ISSUE THREAD

**Issue by antfu** [nuxt/vite#43]
### Is your feature request related to a problem? Please describe.

For example, to get `vite-plugin-md` working, we need to pass options to Vue 2's plugin to let it aware of `.md` files as Vue components. 

```ts
createVuePlugin({
  include: [/\.vue$/, /\.md$/]
})
```

### Describe the solution you'd like

Add an entry or hook for passing options to `vite-plugin-vue2`, `createVuePlugin(optionsHere)`

**Comment by pi0** [comment]
PR welcome @antfu. I think we can extend vite configuration by adding `nuxt.options.vite.vue` option that get's passed to built-in plugins.
