### ISSUE TITLE
Store in index.js is added on a "root" property within state

### ISSUE THREAD

**Issue by dansullivan86** [nuxt/vite#45]
### Versions

nuxt-vite: 0.0.14
nuxt: v2.15.0

### Reproduction

https://codesandbox.io/s/holy-architecture-s4fse?file=/pages/index.vue

### Description

I created a root store by adding a index.js, items are being added at $store.state.root, rather than directly on $store.state

**Comment by pi0** [comment]
Thanks for report. It was a regression. Fixed in v15
