### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nicholasoxford** [nuxt/vite#6]
<img width="852" alt="Screen Shot 2021-02-25 at 4 34 38 PM" src="https://user-images.githubusercontent.com/51415676/109221686-8a544180-7787-11eb-9f01-7870c6646dd8.png">

I ran `npm i -D nuxt-vite` and received `Cannot read property 'length' of undefined `

Maybe I need to change which directory I am in?

**Comment by pi0** [comment]
This seems a NPM bug 😟 Can you please try with `yarn`? (also it is unlikely module works out of the box if your project is using features like plugins, etc)
