### ISSUE TITLE
config.resolve.alias doesn't work

### ISSUE THREAD

**Issue by k-leclere** [nuxt/vite#60]
✔ Builder initialized
 ✔ Nuxt files generated
 > html:/data/ofi/components/common/Footer/FooterNewsletter.vue:2:22: error: Could not resolve "oficommonvuejs/components/Share/BtnSocial.vue" (the plugin "vite:dep-scan" didn't set a resolve directory)

### Versions

nuxt-vite: 0.0.21
nuxt: 2.15.2

### Description
I've this config in nuxt.config for an alias repository on build but there is no resolution of it :
build: {
       extend(config, { isDev }) {
            **config.resolve.alias.oficommonvuejs = path.resolve(__dirname, '../ofi-common-vuejs');**
       }
}

**Comment by reslear** [comment]
@k-leclere https://github.com/nuxt/vite/issues/55#issuecomment-787492624
