### ISSUE TITLE
 Unexpected "<"  when jsx render tag

### ISSUE THREAD

**Issue by Xiamer** [nuxt/vite#63]
### Versions

nuxt-vite: 0.0.22
nuxt: 2.15.2

### e.g.
```js
import AnchoredHeading from './AnchoredHeading.vue'

new Vue({
  el: '#demo',
  render: function (h) {
    return (
      <AnchoredHeading level={1}>
        <span>Hello</span> world!
      </AnchoredHeading>
    )
  }
})
```

### Description

 error: Unexpected "<"

**Comment by pi0** [comment]
Hi. Basic typescript support is added in v23. Please see this example:

- https://github.com/nuxt/vite/blob/f6ad9874ecda2238ae628fb70687551211d265c3/test/fixture/components/JSXComponent.jsx
- https://github.com/nuxt/vite/blob/f6ad9874ecda2238ae628fb70687551211d265c3/test/fixture/pages/index.vue
