### ISSUE TITLE
fix: support asset importing (ssr)

### ISSUE THREAD

**Issue by pi0** [nuxt/vite#7]
template:

```html
<img src="../assets/logo.svg">
```

```
 ERROR  [vite]: Rollup failed to resolve import "assets/logo.svg" from "pages/index.vue?vue&type=template&lang.js".                                                                     22:44:25
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`


 ERROR  Server compiled with errors: [vite]: Rollup failed to resolve import "assets/logo.svg" from "pages/index.vue?vue&type=template&lang.js".                                        22:44:25
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by aysnet1** [comment]
the same error
```
This is most likely unintended because it can break your application at runtime.

If you do want to externalize this module explicitly add it to
build.rollupOptions.external


 ERROR  Server compiled with errors: [vite]: Rollup failed to resolve import "/icons/flutter_dash-w.svg" from "pages\auth\signin.vue?vue&type=template&lang.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (node_modules\vite\dist\node\chunks\dep-00e79b84.js:46594:19)
  at Object.onwarn (node_modules\vite\dist\node\chunks\dep-00e79b84.js:46444:17)
  at Object.onwarn (node_modules\rollup\dist\shared\rollup.js:19639:20)
  at ModuleLoader.handleResolveId (node_modules\rollup\dist\shared\rollup.js:18719:26)
  at node_modules\rollup\dist\shared\rollup.js:18686:22
  at async Promise.all (index 0)
  at async ModuleLoader.fetchStaticDependencies (node_modules\rollup\dist\shared\rollup.js:18684:34)
  at async Promise.all (index 0)
  at async ModuleLoader.fetchModule (node_modules\rollup\dist\shared\rollup.js:18661:9)
  at async Promise.all (index 1)
  at async ModuleLoader.fetchStaticDependencies (node_modules\rollup\dist\shared\rollup.js:18684:34)
  at async Promise.all (index 0)
  at async ModuleLoader.fetchModule (node_modules\rollup\dist\shared\rollup.js:18661:9)
  at async node_modules\rollup\dist\shared\rollup.js:18634:48
  at async Promise.all (index 2)
  at async ModuleLoader.fetchDynamicDependencies (node_modules\rollup\dist\shared\rollup.js:18624:30)
```

**Comment by pi0** [comment]
most of issues resolved with latest version of [vite-plugin-vue](https://github.com/underfin/vite-plugin-vue2). But URL generated by SSR is 404.  (PR to track: #39)

**Comment by WebMBX** [comment]
same error, still not working...

nuxt: 2.15.2
nuxt-vite: 0.0.28

`<img src="logo.svg"/>`

` ERROR  [vite]: Rollup failed to resolve import "logo.svg" from "components/Head.vue?vue&type=template&lang.js".                                                                     
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external``

**Comment by jshimkoski** [comment]
Any status on this? I'd love to jump on the Vite train but the inability to use assets from the static directory is a showstopper.

I'm surprised the content module is marked as working with Vite as its assets are basically required to be served from the static directory.

**Comment by rwwagner90** [comment]
Just ran into this as well. Any updates here?

**Comment by productfrontenddeveloper** [comment]
![CleanShot 2021-05-14 at 21 28 55](https://user-images.githubusercontent.com/38668796/118313436-65a47600-b4fb-11eb-9a3f-e35352fed6ca.png)
v1.0.0

**Comment by pi0** [comment]
@productfrontenddeveloper Would you please make a reproduction or share index.vue?

**Comment by productfrontenddeveloper** [comment]
> @productfrontenddeveloper Would you please make a reproduction or share index.vue?

[index.vue.zip](https://github.com/nuxt/vite/files/6486103/index.vue.zip)

**Comment by rwwagner90** [comment]
@pi0 I see you merged a PR to disable SSR in development. Won't that introduce a lot of gotchas if the dev environment does not support SSR?

**Comment by pi0** [comment]
Yes, you have to be careful about SSR compatibility during development. Due to issues like this and others mentioned in #139, disabling allows having a more stable experience of vite. Hopefully, we can turn SSR back to enabled soon :)

**Comment by productfrontenddeveloper** [comment]
when fixed :(

**Comment by ahmed56734** [comment]
import like this with @ `<img src="@/assets/logo.svg">
`
