### ISSUE TITLE
Replacing `document` with `undefined` cause undefined error on client

### ISSUE THREAD

**Issue by farnabaz** [nuxt/vite#73]
### Versions

nuxt-vite: 0.0.28
nuxt: 2.15.2

### Reproduction

Start the codesandbox and look to console
https://codesandbox.io/s/inspiring-kowalevski-gzy97?file=/nuxt.config.js

### Description

Replacing `document` with `undefined` cause an undefined issue on script injection. 

https://github.com/nuxt/vite/blob/04d01edfa9d5eb94e76736ae95a6394bba375a06/src/server.ts#L44

Modules like color-mode and google-fonts are adding scripts info head and Vite replaces `document` in these scripts and finally it raises undefined error on browser

**Comment by pi0** [comment]
I'm not sure if rollup/vite support syntax aware replacement so going to use `'typeof document'` => `undefined` replacement.
