### ISSUE TITLE
External sass import is broken

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/vite#81]
### Versions

nuxt-vite: v0.0.28
nuxt: v2.15.2

### Reproduction

1. Add global SCSS file
2. Import Vuetify styles, just like they say in docs
```scss
@import '~vuetify/src/styles/settings/_variables.scss';
```

https://github.com/daniluk4000/nuxt-vite-bug

### Description

You will face an error

```
 Server compiled with errors: Can't find stylesheet to import.                                                                                         16:17:53
  ╷
1 │ @import '~vuetify/src/styles/settings/_variables.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  scss\index.scss 1:9      @import
  layouts\default.vue 1:9  root stylesheet
```

**Comment by fdemir** [comment]
I've checked your repository and solved your problem. Firstly, you're trying to import your SCSS file in the wrong way. You have to use css property in nuxt.config.ts file like the following.
```js
  css: ["~/scss/index.scss"],
```
Import path is wrong in index.scss. You have to remove tilde at start of path. Tilde referencing the root path. But vuetify is a module.
```
@import 'vuetify/src/styles/settings/_variables.scss';
```

**Comment by daniluk4000** [comment]
Thanks, will try that, and if it works in my own project will close the issue

**Comment by prochorz** [comment]
```
    vite: {
        resolve: {
            alias: {
                '~ vuetify': 'vuetify'
            }
        }
    },
```

**Comment by daniluk4000** [comment]
> 
> 
> @daniluk4000 Did this solve the issue for you?

Sorry but I can't test, I face issue from #71 with duplicate CSS and can't test

**Comment by antfu** [comment]
Let's keep track on #71
