### ISSUE TITLE
Cannot parse Vue Single File Component with a JSX render function

### ISSUE THREAD

**Issue by Hiswe** [nuxt/vite#82]
### Versions

nuxt-vite: 0.0.28
nuxt: ~~2.14.12~~ 2.15.2

### Reproduction

launch a Nuxt application with a Vue Single File Component using JSX.

The reproduction repo is here: https://github.com/Hiswe/nuxt-vite

### Description

I'm trying to launch a Nuxt application where inside a Vue SFC I use a render function with JSX.
I'm not doing a pure `.jsx` file in order to be able to use some scoped styles.

With a basic setup I have this error:

> [plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.

In the Vite repo I've seen the issue https://github.com/vitejs/vite/issues/1972
It seems that we can avoid the error `Unexpected "<"` by using a `<script lang="jsx">`

But but doing so I have a new error:

> ENOENT: no such file or directory, open '/nuxt-vite/components/template-jsx.vue?vue&type=script&lang.jsx'

I didn't find any other issues related to that (#63 & #65 seems only to concern `.jsx` files)

Do you have any ideas how it can be solved?

Anyway, thanks for your work! I didn't expected to see Vite used with Nuxt 2!

**Comment by TheLearneer** [comment]
I am not sure if it can be the cause but `nuxt >= 2.15.0 is required` is stated in the readme

**Comment by Hiswe** [comment]
> I am not sure if it can be the cause but `nuxt >= 2.15.0 is required` is stated in the readme

I've updated the dependency to 2.15.2 & still the same issue

**Comment by danielroe** [comment]
Should be working in 0.0.36. 😊 Let me know if not.

**Comment by Hiswe** [comment]
@danielroe It's working amazingly fine!
Thanks a lot!
